---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mlkit

<!-- badges: start -->
`r badger::badge_devel('mlkit', 'orange')`
`r badger::badge_code_size('Accelerytics/mlkit')`
`r badger::badge_last_commit('Accelerytics/mlkit')`
<!-- badges: end -->

`mlkit` is a collection of implementations of machine learning algorithms and utilities for data science projects. This packages has initially been developed
and used for the [Supervised Machine Learning](https://www.tinbergen.nl/courses/89/supervised-machine-learning) course that is part of the [MPhil in Business Data Science](https://businessdatascience.nl/home) offered by the [Tinbergen Institute](https://www.tinbergen.nl/home).


## Installation

You can install the development version of `mlkit` from
[GitHub](https://github.com/) with:
``` r
install.packages("devtools")
devtools::install_github("Accelerytics/mlkit")
```


## Bug reports

Found a mistake or inconsistency? [Open a new issue](issues) here on GitHub or [send an email to mathijs@accelerytics.com](mailto:mathijs@accelerytics.com).


## Copyright and License
Copyright 2020 Accelerytics. Content released under the [MIT license](LICENSE), which means you can use this content for any purpose, even for commercial projects.
